remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
title: SCANS

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "SCANS on GitHub":
    - "https://github.com/PARSES-Lab/scans"

nav_external_links:
  - title: SCANS on GitHub
    url: https://github.com/PARSES-Lab/scans

back_to_top: true
back_to_top_text: "Back to top"

